export const DELETE_INGREDIENT_FROM_RECIPE = "DELETE_INGREDIENT_FROM_RECIPE";
export const ADD_INGREDIENT_TO_RECIPE = "ADD_INGREDIENT_TO_RECIPE";
export const FILTER_RECIPE = "FILTER_RECIPE";
export const ADD_RECIPE_TO_BASKET = "ADD_RECIPE_TO_BASKET";
export const SHOW_RECIPES_DETAILS = "SHOW_RECIPE_DETAILS";
